<?php

//require_once '/home/verber/Dropbox/workspace/tdd-mvc-app/app/Router.php';

/**
 * Test class for Router.
 * Generated by PHPUnit on 2011-12-16 at 03:45:59.
 */
class RouterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
       // $this->object = new Router($_GET['uri']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetController().
     */
    public function testGetController()
    {
    	$uri = '/user/';
        $router = new Router($uri);
        $this->assertEquals('user', $router->getController(), "testGetController Fail");
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetAction().
     */
    public function testGetAction()
    {
        $uri = '/user/show/';
        $router = new Router($uri);
        $this->assertEquals('show', $router->getAction(), "testGetAction Fail");
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetArgs().
     */
    public function testGetArgs()
    {
        $uri = '/index/index/id/2/';
        $router = new Router($uri);
        $args = array('id' => '2');
        $this->assertEquals($args, $router->getArgs(), "testGetArgs Fail");
        
        $router->dispatch();
    }
}
?>
